AllCops:
  NewCops: enable
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 30
Style/Documentation:
  Enabled: false
