name: CI
on: [push, pull_request]
jobs:
  elixir:
    name: Build and test elixir solutions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: '1.13.0'
          otp-version: '24.1'
      - name: Run tests
        run: |
          find ./* -name mix.exs -print | \
          awk -F '/' '{print $2}' | \
          xargs -n1 -IDIR bash -c 'cd DIR && mix test'